### ISSUE TITLE
Following the README leads to an error

### ISSUE THREAD

**Issue by jlengrand** [adyen-examples/adyen-testing-suite#1]
When following the READMe, it looks like some dependencies are not installed when trying to run the test suite : 

```


  3) [chromium] › ideal.spec.js:4:1 › iDEAL ========================================================

    browserType.launch: Executable doesn't exist at /Users/julien/Library/Caches/ms-playwright/chromium-939194/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝


```

**Comment by jlengrand** [comment]
Running `npx playwright install` as indicated .

**Comment by jlengrand** [comment]
When running the tests, it looks like I'm having issues with timeouts. Not extremely surprising but we might want to consider increasing them to avoid inconsistent test runs. 


```

  3 failed
    [chromium] › card.spec.js:5:1 › Card ===========================================================
    [chromium] › dropin.spec.js:5:1 › Dropin SEPA ==================================================
    [chromium] › ideal.spec.js:4:1 › iDEAL =========================================================
  1 passed (11s)

  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.
npx playwright test
^C
❯
❯
❯
❯
❯ npx playwright test

Using config at /Users/julien/Developer/adyen/adyen-testing-suite/playwright.config.js

Running 4 tests using 2 workers
  1) [chromium] › dropin.spec.js:5:1 › Dropin SEPA =================================================

    Timeout of 5000ms exceeded.

    Pending operations:
      - expect.toBeVisible at tests/dropin.spec.js:18:60

    Error: expect(received).toBeVisible()

    Call log:
      - waiting for selector "text="SEPA Direct Debit""


      16 |     // click "Continue to checkout"
      17 |     await page.click('text="Continue to checkout"');
    > 18 |     await expect(page.locator('text="SEPA Direct Debit"')).toBeVisible();
         |                                                            ^
      19 |
      20 |     // select SEPA
      21 |     await page.locator('button[aria-label="SEPA Direct Debit"]').click();

        at /Users/julien/Developer/adyen/adyen-testing-suite/tests/dropin.spec.js:18:60
        at WorkerRunner._runTestWithBeforeHooks (/Users/julien/Developer/adyen/adyen-testing-suite/node_modules/@playwright/test/lib/workerRunner.js:499:7)


  1 failed
    [chromium] › dropin.spec.js:5:1 › Dropin SEPA ==================================================
  3 passed (8s)

  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.
```

**Comment by jlengrand** [comment]
Increasing the timeout, I'm still getting errors on the iDEAL test


```

Using config at /Users/julien/Developer/adyen/adyen-testing-suite/playwright.config.js

Running 4 tests using 2 workers
  1) [chromium] › dropin.spec.js:5:1 › Dropin SEPA =================================================

    Error: expect(received).toBeVisible()

    Call log:
      - waiting for selector "text="SEPA Direct Debit""


      16 |     // click "Continue to checkout"
      17 |     await page.click('text="Continue to checkout"');
    > 18 |     await expect(page.locator('text="SEPA Direct Debit"')).toBeVisible();
         |                                                            ^
      19 |
      20 |     // select SEPA
      21 |     await page.locator('button[aria-label="SEPA Direct Debit"]').click();

        at /Users/julien/Developer/adyen/adyen-testing-suite/tests/dropin.spec.js:18:60
        at WorkerRunner._runTestWithBeforeHooks (/Users/julien/Developer/adyen/adyen-testing-suite/node_modules/@playwright/test/lib/workerRunner.js:499:7)


  1 failed
    [chromium] › dropin.spec.js:5:1 › Dropin SEPA ==================================================
  3 passed (7s)

  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.
```

**Comment by gcatanese** [comment]
README now includes `npx playwright install`. The timeout issue is now solved.
